spring:
  datasource:
    url: "jdbc:h2:mem:grade-submission"
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
